language: ruby
before_install: gem install bundler
script: "bundle exec rake spec"
addons:
  code_climate:
    repo_token: ab624e4e0be1ac70631beeb8cb61fed99d511a93d8bf437255a4ff94f69e7836
rvm:
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - ruby-head
  - rbx-2
matrix:
  allow_failures:
      - rvm: rbx-2
      - rvm: ruby-head
notifications:
  email:
    - roberto.ciatti@overhilllab.com
    - matteo.foccoli@overhilllab.com
